# https://docs.docker.com/compose/compose-file/compose-versioning/#compatibility-matrix
# => run: docker version để biết enginer version bao nhiêu
# version: "3.9" 
services:
  nginx:
    container_name: my-nginx
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./frontend-vite/dist:/usr/share/nginx/html/
      - ./expamle/default.conf:/etc/nginx/conf.d/default.conf

  db-mongo:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: zjnkill18
      MONGO_INITDB_ROOT_PASSWORD: Nho812005
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  be-nest:
    build:
      context: ./backend-nestjs
      dockerfile: Dockerfile
    # restart: unless-stopped
    environment:
      - PORT=8088
      - NODE_ENV=production
      - MONGO_URL= mongodb+srv://zjnkill18:Nho812005@db-mongo.1h2xbl9.mongodb.net/backend-nestJS
      # - DB_HOST=host.docker.internal

    ports:
      - 8088:8088
volumes:
  mongodb:

    #stop current running nginx
    # docker compose -p app-bookstore up -d
